# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_UB_UBUS_SIM_DECODER) += ub-sim-decoder.o

ub-sim-decoder-y := ub_sim_decoder_main.o ub_sim_decoder_service.o \
		    ub_sim_decoder_ctrl.o ub_sim_decoder_backend.o
